trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'reactmetal'
    appType: 'webAppLinux'
    appName: 'metalreact'
    package: '$(System.ArtifactsDirectory)/build.zip'
- task: DownloadBuildArtifacts@0
  inputs:
    artifactName: 'build'  # Name of the artifact produced by your build pipeline
    downloadPath: '$(System.ArtifactsDirectory)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'reactmetal'
    appType: 'webAppLinux'
    appName: 'metalreact'
    package: '$(System.ArtifactsDirectory)/build.zip'
