import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import HydrogenLayout from "@/layouts/layout";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["devanagari", "latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Metal Recycling App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <HydrogenLayout>{children}</HydrogenLayout>
        <Toaster toastOptions={{ position: "top-right" }} />
      </body>
    </html>
  );
}
