import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import HydrogenLayout from "@/layouts/layout";
import { Toaster } from "react-hot-toast";
import dynamic from "next/dynamic";

const NextProgress = dynamic(() => import("@/components/next-progress"), {
  ssr: false,
});

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["devanagari", "latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Metal Recycling App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NextProgress />
        {children}
        <Toaster position="top-right" />
        <HydrogenLayout>{children}</HydrogenLayout>
      </body>
    </html>
  );
}
