import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import HydrogenLayout from "@/layouts/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Metal Recycling App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HydrogenLayout>{children}</HydrogenLayout>
        <Toaster toastOptions={{ position: "top-right" }} />
      </body>
    </html>
  );
}
